### ISSUE TITLE
Projects Voting

### ISSUE THREAD

**Issue by allamiro** [SudamITPro-Dev/projects#11]
Vote Here

**Comment by tagwaesam** [comment]
7 android dating app with chat  and voice call functions

3. Prject 1  developing website templates / html pages  for small companies maxium 4 or 5 pages

**Comment by shahdaaosman** [comment]
1. developing an open source  invoice management system

2. design a protofilo website.

**Comment by shrafco1** [comment]
1- Solve brain teaser problems
2- developing website templates/ html pages for small companies maximum 4 or 5 pages.
